version: '3'
services:
  atlas-g:
    build:
      context: './gogasm/'
    image: atlas-g
    container_name: atlas-g
    hostname: atlas-g
    expose:
      - 80:8081
    networks:
        atlas:
          aliases:
            - atlas-g
    restart: on-failure
    env_file: .env-atlas-g
    
  atlas-r:
    build:
      context: './redis/'
    image: atlas-r
    container_name: atlas-r
    hostname: atlas-g
    #command: redis-server /usr/redis/redis-cluster.conf --requirepass changeme
    expose:
      - "6379"
    networks:
        atlas:
          aliases:
            - atlas-r
    restart: on-failure
    env_file: .env-atlas-r
    volumes:
      - /home/${USER}/.atlas/AtlasTools/RedisDatabase/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/${USER}/.atlas/data:/data

  atlas-s:
    build:
      context: './atlas/'
    image: atlas-s
    depends_on:
            - atlas-r
    container_name: atlas-s
    hostname: atlas-s
    networks:
      atlas:
        aliases:
          - atlas-s
    ports:
      - '${ATLASQUERYPORT}:${ATLASQUERYPORT}/udp' #Query UDP
      - '${ATLASQUERYPORT}:${ATLASQUERYPORT}' #Query TCP
      - '${SEAMLESSPORT}:${SEAMLESSPORT}' #Seamless TCP
      - '${GAMEPORT1}:${GAMEPORT1}/udp' #Gameport1 UDP
      - '${GAMEPORT2}:${GAMEPORT2}/udp' #Gameport2 UDP
      - '${RCONPORT}:${RCONPORT}' #RCON Port TCP
    expose:
      - "61208"
    env_file: .env-atlas-s
    volumes:
      - "~/.atlas:/home/steam/.atlas"
    command:
      - /bin/sh
      - -c
      - |
          screen -dmS atlas -L -U /home/steam/bin/start_server.sh
          screen -dmS glances -L -U glances -w
          #screen -dmS vmstat -L -U websocketd --port 8081 --staticdir=/home/steam/web /usr/bin/vmstat 1 1
          tail -f /dev/null

networks:
  atlas:
    driver: bridge
