version: '3'
services:
  atlas-r:
    build:
      context: './redis/'
    image: atlas-r
    container_name: atlas-r
    #command: redis-server /usr/redis/redis-cluster.conf --requirepass changeme
    expose:
      - "6379"
    networks:
        atlas:
          aliases:
            - atlas-r
    restart: on-failure
    env_file: .env-atlas-r

  atlas-s:
    build:
      context: './atlas/'
    image: atlas-s
    depends_on:
            - atlas-r
    container_name: atlas-s
    networks:
      atlas:
        aliases:
          - atlas-s
    ports:
      - 5701:5701
      - 5700:5700
      - 57500:57500
      - 57501:57501
      - 27020:27020
    env_file: .env-atlas-s

networks:
  atlas:
    driver: bridge
