debug = false
logLevel = "DEBUG"


[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[retry]

[acme]
acmeLogging = true
email = "zate75@gmail.com"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
onHostRule = true
 # [acme.httpChallenge]
 #   entryPoint = "http"
 [acme.tlsChallenge]

[[acme.domains]]
  main = "atlas.zate.systems"

[api]
entrypoint = "dashboard"

[docker]

endpoint = "unix:///var/run/docker.sock"

domain = "atlas.zate.systems"

watch = true
exposedByDefault = false
network = "atlas"