debug = true
logLevel = "DEBUG"


[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[retry]

[acme]
acmeLogging = true
email = "zate75@gmail.com"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
onHostRule = true
[acme.tlsChallenge]

[[acme.domains]]
  main = "atlas.zate.systems"

[docker]

endpoint = "unix:///var/run/docker.sock"

domain = "zate.systems"

watch = true
exposedByDefault = false
# network = "atlas"